{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNgi8GSzYqv8cIGe95q+j2b",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/JA-RgueZ/FEDRO128/blob/main/main.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import json\n",
        "from fastapi import FastAPI, HTTPException\n",
        "from google.oauth2 import service_account\n",
        "import gspread\n",
        "\n",
        "# --- METADATA DEL PROYECTO ---\n",
        "# Usamos VERSION para trazabilidad en los logs de Railway\n",
        "VERSION = \"1.0.3-stable\"\n",
        "app = FastAPI(title=\"FEDRO API\", version=VERSION)\n",
        "\n",
        "# --- CAPA DE CONFIANZA: IDENTIDAD DE DATOS (CUENTA FEDRO) ---\n",
        "def get_sheets_client():\n",
        "    # Recupera el JSON de la Service Account desde las variables de entorno\n",
        "    creds_json = os.environ.get(\"GOOGLE_CREDS_JSON\")\n",
        "    if not creds_json:\n",
        "        raise ValueError(\"Error: GOOGLE_CREDS_JSON no configurada en Railway.\")\n",
        "\n",
        "    info_json = json.loads(creds_json)\n",
        "\n",
        "    # Definición de Scopes para evitar el error 403\n",
        "    # Esto permite que la Service Account \"entre\" a Sheets y Drive\n",
        "    scopes = [\n",
        "        'https://www.googleapis.com/auth/spreadsheets',\n",
        "        'https://www.googleapis.com/auth/drive'\n",
        "    ]\n",
        "\n",
        "    creds = service_account.Credentials.from_service_account_info(\n",
        "        info_json,\n",
        "        scopes=scopes\n",
        "    )\n",
        "    return gspread.authorize(creds)\n",
        "\n",
        "# --- ENDPOINT DE SALUD (HEALTH CHECK) ---\n",
        "@app.get(\"/\")\n",
        "def health_check():\n",
        "    # Verifica que las llaves maestras estén cargadas en el entorno\n",
        "    return {\n",
        "        \"status\": \"FEDRO Online\",\n",
        "        \"version\": VERSION,\n",
        "        \"database\": \"FEDRO128 / Cuadro\",\n",
        "        \"ia_brain\": \"Configurado\" if os.environ.get(\"GEMINI_API_KEY\") else \"Faltante\"\n",
        "    }\n",
        "\n",
        "# --- ENDPOINT DE IDENTIDAD: BÚSQUEDA POR TELÉFONO (ETAPA 2) ---\n",
        "# Este endpoint vincula el WhatsApp entrante con el RUT y Grado del QH\n",
        "@app.get(\"/auth/perfil/{telefono}\")\n",
        "def get_perfil(telefono: str):\n",
        "    try:\n",
        "        client = get_sheets_client()\n",
        "\n",
        "        # 1. Abre el archivo principal definido en el plan (FEDRO128)\n",
        "        spreadsheet = client.open(\"FEDRO128\")\n",
        "\n",
        "        # 2. Selecciona la pestaña específica de la base de miembros\n",
        "        sheet = spreadsheet.worksheet(\"Cuadro\")\n",
        "\n",
        "        # 3. Busca el teléfono en la hoja para identificar al QH\n",
        "        cell = sheet.find(telefono)\n",
        "\n",
        "        if not cell:\n",
        "            return {\"identificado\": False, \"error\": \"QH no encontrado\"}\n",
        "\n",
        "        # 4. Extrae los datos (usando la nueva información de columnas)\n",
        "        # Columnas: RUT, DV, Apellido Paterno, Apellido Materno, Nombres, Nombre simple, Fnac, edad, Grado, Tipo Miembro, Celular, Email\n",
        "        row = sheet.row_values(cell.row)\n",
        "\n",
        "        rut_value = row[0] # RUT\n",
        "        # Combinar Nombres (índice 4), Apellido Paterno (índice 2), Apellido Materno (índice 3)\n",
        "        nombre_completo_value = f\"{row[4]} {row[2]} {row[3]}\"\n",
        "\n",
        "        grado_value = 0 # Default value if conversion fails\n",
        "        try:\n",
        "            # 'Grado' está en el índice 8 según la lista de columnas proporcionada\n",
        "            grado_value = int(row[8])\n",
        "        except ValueError:\n",
        "            # If conversion fails, print a warning and use the default value\n",
        "            print(f\"Advertencia: El valor de Grado '{row[8]}' no es un entero para el teléfono {telefono}. Usando 0 como predeterminado.\")\n",
        "\n",
        "        # Retorna el Perfil/Oficio para determinar comandos autorizados en n8n\n",
        "        return {\n",
        "            \"identificado\": True,\n",
        "            \"rut\": rut_value,\n",
        "            \"nombre_completo\": nombre_completo_value,\n",
        "            \"grado\": grado_value,\n",
        "            \"status\": \"Regular\",\n",
        "            \"api_version\": VERSION\n",
        "        }\n",
        "\n",
        "    except Exception as e:\n",
        "        # Captura errores de permisos (403) o conexión para debug en logs\n",
        "        raise HTTPException(status_code=500, detail=f\"Error en FEDRO-API: {str(e)}\")"
      ],
      "metadata": {
        "id": "XiKWyZwhMGhv"
      },
      "execution_count": 3,
      "outputs": []
    }
  ]
}